import { test, expect } from "@playwright/test";
import sharp from "sharp";

test("private studio: free controls, queued independent drafts, exact approved PNG and truthful handoff", async ({ page, browser }) => {
  test.skip(!process.env.E2E_EMAIL || !process.env.E2E_PASSWORD, "Set credentials for an explicitly seeded, dedicated test owner and run the web + worker.");
  await page.goto("/");
  await page.getByLabel("Email", { exact: true }).fill(process.env.E2E_EMAIL!);
  await page.getByLabel("Password", { exact: true }).fill(process.env.E2E_PASSWORD!);
  await page.getByRole("button", { name: "Enter your studio" }).click();
  await expect(page.getByRole("heading", { name: "How does today feel?" })).toBeVisible();
  await page.screenshot({ path: ".runtime/studio-desktop.png" });
  const before = await (await page.request.get("/api/studio")).json();
  expect(before.entry).not.toBeNull();
  const generated: unknown[] = [];
  page.on("request", (request) => {
    if (request.url().endsWith("/api/action") && request.postDataJSON()?.action === "generate") generated.push(request.postDataJSON());
  });
  await page.getByLabel("New haikus", { exact: true }).fill("5");
  await page.getByLabel("New artworks", { exact: true }).fill("2");
  expect(generated).toHaveLength(0);
  await expect(page.getByText("5 × 2 = 10 possible new pairings")).toBeVisible();
  await page.getByRole("button", { name: "Create new samples" }).click();
  await expect(page.getByRole("status")).toContainText("5 haikus + 2 artworks queued");
  expect(generated).toHaveLength(1);
  await expect.poll(async () => {
    const state = await (await page.request.get("/api/studio")).json();
    return [state.poems.length - before.poems.length, state.artworks.length - before.artworks.length];
  }, { timeout: 40_000 }).toEqual([5, 2]);
  const after = await (await page.request.get("/api/studio")).json();
  expect(after.defaults.haikuCount).toBe(before.defaults.haikuCount);
  expect(after.entry.selectedCandidateId).toBe(before.entry.selectedCandidateId);
  await page.locator(".poem-card").first().click();
  await page.locator(".art-card").first().click();
  await page.getByRole("button", { name: "Save composition", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("New immutable revision saved");
  await page.getByRole("button", { name: "Review saved revision" }).click();
  await page.getByRole("button", { name: "Render exact review" }).click();
  await expect(page.locator(".final-image")).toHaveCount(2);
  await expect(page.getByRole("button", { name: "Approve export", exact: true })).toBeDisabled();
  await page.getByLabel("I reviewed both final images").check();
  await page.getByRole("button", { name: "Approve export", exact: true }).click();
  await page.getByRole("button", { name: "Release approved downloads" }).click();
  const download = page.getByRole("link", { name: "Square PNG" });
  await expect(download).toBeVisible();
  const exportUrl = (await download.getAttribute("href"))!;
  const png = await page.request.get(exportUrl);
  expect(png.status()).toBe(200);
  expect(png.headers()["content-disposition"]).toContain("attachment");
  expect(await sharp(await png.body()).metadata()).toMatchObject({ width: 1080, height: 1080, format: "png" });
  await page.getByRole("button", { name: "Mark handed off" }).click();
  await expect(page.getByRole("status")).toContainText("publication remains unverified");
  await page.getByRole("button", { name: "Cancel approval" }).click();
  expect((await page.request.get(exportUrl)).status()).toBe(409);
  expect((await page.request.post("/api/action", { headers: { origin: "https://untrusted.example" }, data: { action: "release", data: {} } })).status()).toBe(403);
  const stranger = await browser.newContext();
  expect((await stranger.request.get(`http://localhost:3000/api/media/${after.artworks[0].assetId}`)).status()).toBe(401);
  await stranger.close();
  await page.getByRole("button", { name: "The Almanac", exact: true }).click();
  await expect(page.getByRole("heading", { name: "The Haiku Almanac" })).toBeVisible();
  await page.getByRole("button", { name: "Settings", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Your creative rhythm." })).toBeVisible();
  await page.getByRole("button", { name: "Today", exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.getByRole("heading", { name: "How does today feel?" })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: ".runtime/studio-mobile.png" });
});
